name: 'CD: Deploy to Prod Domain'

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_run:
    workflows:
      - 'CI: Integrate Preview to Prod'
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Vercel Production Domain
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: prod

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.0.4

      - name: Install Vercel CLI
        run: pnpm i --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # Running `vercel build` will result in `next build` being ran.
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      # By using the `--prebuilt` option - in conjunction with the
      # `vercel build` command - this will allow us to deploy to Vercel without
      # the need to share any source code.
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --env SARA_STAGE="prod" --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
