name: Increment Package Version

on:
  workflow_run:
    workflows:
      - "CI: Integrate Main to Preview"
    types:
      - completed
  workflow_dispatch:
    inputs:
      incrementType:
        description: 'Type of version increment (patch, minor, major)'
        required: true
        default: 'patch'

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Increment version
        run: |
          OLD_VERSION=$(node -p "require('./package.json').version")
          NEW_VERSION=$(npm version ${{ github.event.inputs.incrementType }} --no-git-tag-version)
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "chore(release): increment ${{ github.event.inputs.incrementType }} version from $OLD_VERSION to $NEW_VERSION"
          git push
