name: "CI: Integrate Main to Preview"

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  schedule:
    # Trigger everyday at 14:00 UTC (6 AM PST)
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  test:
    name: Run CI tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # `pnpm` needs to be installed before we setup Node and use it as a cache
      # with `pnpm`
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      # Note that while our Lambda backend uses Node 20 and Vercel also has
      # support for it it is currently in beta - thus use 18 for now
      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Vercel CLI
        run: pnpm i --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # By default the `vercel build` command will build `preview` artifacts
      # that can later be used to deploy to `preview` deployments.
      #
      # Running `vercel build` will result in `next build` being ran.
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Docker images
        run: docker-compose pull

      - name: Run Redis test DB
        run: docker-compose up -d

      # Export NEXTAUTH_URL as localhost when running in GitHub Actions to
      # avoid UntrustedHost error: https://authjs.dev/reference/core/errors/#untrustedhost
      # Note that this isn't a pattern to follow for any Vercel deployments
      #
      # We use a randomly generated `AUTH_SECRET` as well to ensure we can run
      # locally
      - name: Run CI tests
        run: |
          export NEXTAUTH_URL="http://localhost:3000"
          export AUTH_SECRET="8604b92966b197c12aab26f66aa8596a"
          pnpm run start &
          # You shouldn't need to sleep here to let the NextJS server come up as
          # we need to compile our tests with `tsc` before running them which
          # will consume some time
          pnpm run test

      - name: Stop Redis test DB
        if: always()
        run: docker-compose down

  integrate:
    name: Integrate to Preview branch
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Version Number
        id: package_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Extract Changelog Entries
        run: |
          CHANGELOG_CONTENT="$(awk '/# Release Notes/{flag=1; next} /## Version/{flag=0} flag' CHANGELOG.md)"
          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        
      - name: Retrieve Commit Logs
        id: commit_logs
        run: |
          # Assuming 'main' and 'preview' are branch names
          logs=$(git log --oneline preview..main)
          echo "::set-output name=LOGS::${logs//%/%25}"
          
      - name: Merge main into preview as fast-forward
        run: |
          git fetch origin
          git checkout -b preview --track origin/preview
          git merge --ff-only origin/main
          # Amend the commit to include version, changelog, and commit logs
          git commit --amend -m "Merge main into preview: v${{ steps.version_number.outputs.VERSION }} - ${{ steps.changelog.outputs.CHANGELOG }}
          
          Integrated commits:
          ${{ steps.commit_logs.outputs.LOGS }}"
          git push origin preview