name: Promote to Preview

env:
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run CI tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # `pnpm` needs to be installed before we setup Node and use it as a cache
      # with `pnpm`
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      # Note that while our Lambda backend uses Node 20 and Vercel also has
      # support for it it is currently in beta - thus use 18 for now
      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run CI tests
        run: |
          pnpm run dev &
          echo "Sleeping for 10 seconds to let 'dev' build"
          sleep 10
          pnpm run test

  deploy:
    name: Deploy to Preview branch
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Merge into preview
        run: |
          git fetch -a --prune
          git checkout preview
          get merge main